### ISSUE TITLE
Fix todo-action

### ISSUE THREAD

**Issue by JuniorJPDJ** [FUMR/tidal-async#58]
It wasn't updating issues pretty long.

**Comment by wvffle** [comment]
It's only 7 issues that are broken, so is there a point to fix them? We might as well close them manually when we remove the TODOs

**Comment by JuniorJPDJ** [comment]
That's not about closing them, it's about updating their body.
Eg. tasks to do.

**Comment by JuniorJPDJ** [comment]
I was playing a bit with todo-actions and it didn't edit issues as I said before.
In 227a9648e14fdb1d286345fd65fd66d608989084 I moved #19 to #63 and in ce09117c564e2f40b76f32a0c05bd97baab69575 I tried to edit TODO item. It wasn't edited at all.

**Comment by JuniorJPDJ** [comment]
Oh never mind, It just took a few minutes to edit. It's edited! It works! I close this.

**Comment by JuniorJPDJ** [comment]
I just migrated almost all issues/TODOs to new bot and rephrased them a bit if those were badly written.
