### ISSUE TITLE
Dependency not found

### ISSUE THREAD

**Issue by pythonInRelay** [FUMR/tidal-async#83]
```
~[Downloads]/t/tidal-async on master ❯ poetry install                                         at 15:48:44
Creating virtualenv tidal-async-6aH-m42I-py3.9 in /home/dedesvik/.cache/pypoetry/virtualenvs
Updating dependencies
Resolving dependencies... (2.0s)

  RuntimeError

  The dependency name for http-seekable-file does not match the actual package's name: httpseekablefile

  at ~/.poetry/lib/poetry/puzzle/provider.py:291 in get_package_from_directory
      287│         )
      288│
      289│         if name and name != package.name:
      290│             # For now, the dependency's name must match the actual package's name
    → 291│             raise RuntimeError(
      292│                 "The dependency name for {} does not match the actual package's name: {}".format(
      293│                     name, package.name
      294│                 )
      295│             )
```

How are you supposed to install and use this anyway? I just want my X-Tidal-Token...

**Comment by JuniorJPDJ** [comment]
If you just want to extract X-Tidal-Token you can use this code: https://github.com/FUMR/tidal-async/blob/master/tidal_async/utils.py#L123

About install problem: I probably changed something in other package and forget to update it here. Sorry. I'll do this in a few days as now I've loads of things to do.

Someone should generate some docs anyway so we can show some usage here.
Now it's very plain and probably fails in some ways now as DASH is now mandatory and it's work in progress on FUMR side.
